- name: Import Couchbase Server repo
  shell: |
    curl -O https://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-6-amd64.deb
    sudo dpkg -i ./couchbase-release-1.0-6-amd64.deb
    rm -rf ./couchbase-release-1.0-6-amd64.deb
    
- name: Install Couchbase Server Community
  apt:
    name: couchbase-server-community
    update_cache: yes