# Install Couchbase
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# Configure Couchbase

# set soft link
- name: set soft link
  shell: |
    ln -sb /opt/couchbase  /data/wwwroot/couchbase
    ln -sb /opt/couchbase/var/lib/couchbase/config /data/config/couchbase
    ln -sb /opt/couchbase/var/lib/couchbase/logs /data/logs/couchbase
# display version and service state of components
- name: Get Couchbase version
  shell: sudo sh -c "cat /opt/couchbase/VERSION.txt  1>> /data/logs/install_version.txt"

- name: Check Couchbase Service
  shell: systemctl status couchbase-server | grep Active*
  register: check_couchbase_service
  notify: check_couchbase_service