# from: https://docs.couchbase.com/server/6.5/install/rhel-suse-install-intro.html

- name: Import Couchbase Server repo
  shell: |
    curl -O https://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-x86_64.rpm
    sudo rpm -i ./couchbase-release-1.0-x86_64.rpm
    rm -rf ./couchbase-release-1.0-x86_64.rpm
    
- name: Install Couchbase Server Community
  yum:
    name: couchbase-server-community
    update_cache: yes

# On Red Hat Enterprise and CentOS, it’s recommended that you increase the maximum process limits for Couchbase
- name: Setting Max Process Limits
  template:
    src: 91-couchbase.conf
    dest: /etc/security/limits.d/91-couchbase.conf